# Run the below command when you edit .drone.yml
#   drone secure --repo haya14busa/gosum --in .drone.sec.yaml
#
build:
  test:
    image: golang
    commands:
      - go get -d -v -t ./...
      - go test -v ./...
  lint:
    image: golang
    environment:
      - REVIEWDOG_GITHUB_API_TOKEN=$$REVIEWDOG_GITHUB_API_TOKEN
    commands:
      - go get github.com/haya14busa/reviewdog/cmd/reviewdog
      - go get github.com/golang/lint/golint
      - go get honnef.co/go/unused/cmd/unused
      - go get github.com/kisielk/errcheck
      - go get honnef.co/go/staticcheck/cmd/staticcheck
      - go get honnef.co/go/simple/cmd/gosimple
      - |
        go tool vet -all -shadowstrict . 2>&1 | reviewdog -f=govet -ci=droneio
      - |
        golint ./... | reviewdog -f=golint -ci=droneio
      - |
        unused ./... | reviewdog -efm="%f:%l:%c: %m" -name=unused -ci=droneio
      - |
        errcheck -asserts -ignoretests -blank ./... | reviewdog -efm="%f:%l:%c:%m" -name=errcheck -ci=droneio
      - |
        staticcheck ./... | reviewdog -efm="%f:%l:%c: %m" -name=staticcheck -ci=droneio
      - |
        gosimple ./... | reviewdog -efm="%f:%l:%c: %m" -name=gosimple -ci=droneio
    when:
      event: pull_request
